site_name: Geo4Lib
site_url: https://geo4lib.org

theme:
  name: material
  variant: modern
  logo: images/logo-small.png
  custom_dir: overrides
  favicon: images/logo.png
  palette:
    scheme: default
    primary: green
    accent: green
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.top
    - toc.follow

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - meta
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - toc:
      toc_depth: 2
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

nav:
  - 'Home': 'index.md'
  - 'About' : 'about.md'
  - 'Projects': 'projects.md'
  - 'Events' : 'events.md'
  - 'Get Involved': 'get-involved.md'
  - 'Roles': 'roles.md'
  - 'Related Communities': 'related-communities.md'
  - 'Blog': 'blog/index.md'
