site_name: Geo4Lib
site_url: https://geo4lib.org

theme:
  name: material
  palette:
    - primary: green
    - accent: deep purple

features:
  - navigation.expand
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.instant
  - navigation.tabs
  - navigation.integrated
  - toc.follow


  
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - meta
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - toc:
      toc_depth: 1
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - blog:
      archive: false
      post_readtime: false
      post_date_format: medium
      post_url_date_format: yyyy
      archive_date_format: yyyy
      post_excerpt_separator: <!-- more -->

nav:
  - 'About' : 'about.md'
  - 'Projects': 'projects.md'
  - 'Events' : 'events.md'
  - 'Get Involved': 'get-involved.md'
  - 'Roles': 'roles.md'
  - 'Related Communities': 'related-communities.md'
  - 'Blog': 'blog/index.md'

