site_name: Geo4Lib

theme:
  name: material
  palette:
    - primary: green
    - accent: deep purple

features:
  - content.code.copy
  - content.code.annotate
  - navigation.expand
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - toc.follow
  - toc.integrate
  - tags: {}
    index_page: tags.md



  
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - meta
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - toc:
      toc_depth: 2
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - blog:
      categories: true
      archive: true
      post_readtime: false
      post_date_format: medium
      post_url_date_format: yyyy
      archive_date_format: yyyy
      post_excerpt_separator: <!-- more -->

